サーバー再起動コマンドを追加
traPtitech/DevOpsBot pull request #21
Opened 2021-12-29 17:37 UTC by MotoyaAsahina

2021-12-31 07:16 UTC, MotoyaAsahina commented
ログをzapのloggerに記録していただけなので、ログファイルに保存する

2021-12-31 14:15 UTC, hijiki51 requested changes

2021-12-31 14:15 UTC, hijiki51 commented on server.go
> +		Set("Accept", "application/json").
"Accept"はRequestを受け取る側が「こういう形式のものを受け取れますよ」ということを示すために設定するヘッダーです。

それに対して送る側は「このリクエストはこういう形式のものを含んでいますよ」ということを設定するヘッダーが存在し、それは"Content-Type"というものです。

今回はリクエストを送る側なので"Content-Type"を付けてほしいです。

2021-12-31 14:15 UTC, hijiki51 commented on server.go
> +		Set("Accept", "application/json").
https://developer.mozilla.org/ja/docs/Web/HTTP/Headers/Content-Type

2021-12-31 14:15 UTC, hijiki51 commented on server.go
> +		ctx.L().Error("failed to post request", zap.Error(err))
エラーメッセージこれだと読んだときによくわからないから`failed to restart request`みたいに何をpostしたのか書いておいてほしい

2021-12-31 14:15 UTC, hijiki51 commented on server.go
> +		Body(bytes.NewBufferString(fmt.Sprintf("{ \"reboot\": { \"type\": \"%s\" } }", args[0]))).
requestBodyをstringでコーディングするのは読みにくいし、メンテナンスコスト上がるので、他のところと同じようにMapでいい感じにするか、もしくはstruct作ってjson.Marshalして渡してほしい

このサイズなら大した影響がないというのはそうだけどね

2021-12-31 14:15 UTC, hijiki51 requested changes
ログの保存回りも引き続きお願いします。

2021-12-31 17:42 UTC, MotoyaAsahina commented
- ログファイル名：`exec-m011-restart-1640792561`
ログファイル内容：
```txt
Request
- URL: https://compute.tyo1.conoha.io/v2/1864e71d2deb46f6b47526b69c65a45d/servers/997d6052-4b17-4500-8d41-c08fb9667aae/action
- RestartType: HARD
Response
- Header: map[Content-Length:[91] Content-Type:[application/json] Date:[Fri, 31 Dec 2021 17:19:36 GMT] Server:[Apache]]
- Body: {"unauthorized":{"message":"The request you have made requires authentication","code":401}}
- Status: 401 Unauthorized (Expect: 202)
```
のようにしました。

- `exec-log`に対応、`exec-log m011 restart 1640792561`のように、`exec-log`でserviceとserverの両方のログを取れるようにしましたが、今の状態だとservice名とserver名が重複するとダメです。
`exec-log service trap-collection deploy-backend 1640792561`、`exec-log server m011 restart 1640792561`のようにするのが良いでしょうか。その場合、ログファイル名にserviceとserverを含んだ方が良いでしょうか。

2021-12-31 17:56 UTC, MotoyaAsahina commented on server.go
> +		return ctx.ReplyFailure(fmt.Sprintf(":x: An error has occurred while executing command. %s", cite(ctx.P.Message.ID)))
ここで終了したときにログファイルが保存されていてほしさがあるけど、ここで失敗しない気がする

2022-01-01 22:05 UTC, hijiki51 requested changes

2022-01-01 22:06 UTC, hijiki51 commented on server.go
> +	"io/ioutil"
基本的にioとosに分割した感じだからそんな困らないと思う

ここら辺参考に
https://future-architect.github.io/articles/20210210/

2022-01-01 22:31 UTC, hijiki51 commented on server.go
> +		return ctx.ReplyFailure(fmt.Sprintf(":x: An error has occurred while executing command. %s", cite(ctx.P.Message.ID)))
```
An error is returned if caused by client policy (such as CheckRedirect), or failure to speak HTTP (such as a network connectivity problem).
```

ってことなのでありうるとしたらネットワークやfirewallの設定間違えたりした時やConohaのネットワークが死んでる時かな(500とか帰ってもエラーにはならない)。ただそれはログに保存する必要性は薄くて、traQにメッセージで返せば十分だと思う。

2022-01-01 22:45 UTC, hijiki51 commented
コマンドに関しては意図を明示するために
`exec-log service trap-collection deploy-backend 1640792561`、`exec-log server m011 restart 1640792561`
の形にしてほしいです。
ファイル名に関しては後方互換性切れたりして考えること多いのでとりあえずそのままで

2022-01-02 06:57 UTC, hijiki51 requested changes
ここ以外はよさそうです！token周りだけ最後よろしくお願いします

2022-01-02 06:57 UTC, hijiki51 commented on config.go
> +	ConohaApiToken    string   `yaml:"conohaApiToken"`
これX-Auth-Tokenに着けてるんだけけど、このTokenは固定値ではなくて、usernameとapikeyを使って発行して使うものです。

なのでその部分の処理が必要ですね（気づくの遅れてすみません）
https://www.conoha.jp/docs/identity-post_tokens.php

2022-01-02 15:28 UTC, hijiki51 requested changes

2022-01-02 15:28 UTC, hijiki51 commented on server.go
> +	return responseMap["access"].(Map)["token"].(Map)["id"].(string), nil
さすがにMapで持つには複雑すぎるかな、読みにくいので型作ってほしい（できればリクエストのほうも）

2022-01-02 16:47 UTC, MotoyaAsahina commented on server.go
> +	return responseMap["access"].(Map)["token"].(Map)["id"].(string), nil
修正しました！

2022-01-03 13:25 UTC, hijiki51 requested changes

2022-01-03 13:25 UTC, hijiki51 commented on server.go
> +	type PasswordCredentials struct {
外部からアクセスする必要がないのでこことAuthの型のスコープprivate(最初小文字)にしてほしいです。

2022-01-04 01:42 UTC, MotoyaAsahina commented on server.go
> +	type PasswordCredentials struct {
:kan:

2022-01-04 11:47 UTC, hijiki51 approved these changes
良さそうです！ありがとうございます！

2022-01-04 11:50 UTC, merged

2022-01-04 14:22 UTC, hijiki51 commented on server.go
> +		Set("Accept", "application/json").
これ大嘘らしいね

2022-01-04 14:30 UTC, hijiki51 commented on server.go
> +		Set("Accept", "application/json").
ごめんなさい